name: spotify-genre-prediction
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - setuptools
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - ipykernel
  - joblib
  - streamlit
  # Audio upload / feature extraction
  - librosa
  - pysoundfile
  - audioread
  - ffmpeg
  - pip:
      - kaggle
